name: Bug report
description: Report a bug in the SharePoint Audit Agent
labels: [bug]
body:
  - type: textarea
    attributes: { label: What happened? }
  - type: textarea
    attributes: { label: Reproduction steps }
  - type: textarea
    attributes: { label: Logs / output (redact PII) }
